### GENERAL SETTINGS ###

# Site settings
title: "CMS VOICES"
description: "Homepage of @CMSvoices from the CMS Experiment at CERN."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://cern.ch/cms-voices"

# Build settings
markdown: kramdown
permalink: /:title

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: flickr, linkedin, instagram, tumblr, dribble etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/CMSexperiment
  - title: facebook
    url: https://facebook.com/CMSexperiment
  - title: google-plus
    url: https://plus.google.com/+CMSExperiment
